spring:
    data:
        redis: # redis配置
            host: localhost
            port: 6379
            password: 123456
            database: 0 # 指定使用哪个数据库
            lettuce:
                pool: # 连接池配置
                    # 最大连接数
                    max-active: 10
                    # 最大阻塞等待时间
                    max-wait: 3000
                    # 最大空闲连接
                    max-idle: 5
                    # 最小空闲连接
                    min-idle: 2
                    enabled: true
